### ISSUE TITLE
Error: Failed to call done in a stream handler before 30000ms timeout

### ISSUE THREAD

**Issue by jeconner** [spalger/gulp-jshint#103]
Given this task:

```javascript
gulp.task('jshint', function() {
   var jsHintOptions = {
      globalstrict: true,
      browser: true,
      globals: {
         angular: true,
         console: true,
         jQuery: true,
         $: true,
      },
      shadow: "inner",
      sub: true,
      strict: false,
      laxcomma: true
   };

   gulp.src(globalSearchFiles, {base: './'})
      .pipe(jshint(jsHintOptions))
      .pipe(jshint.reporter('jshint-summary', {
         verbose: true,
         statistics: true
      }))
      .pipe(jshint.reporter('fail'));      
});
```

I get the following error after all gulp tasks have finished:
```
[INFO] [12:47:53] Starting 'jshint'...
[INFO] [12:47:53] Finished 'jshint' after 43 ms
...
[INFO] events.js:72
[INFO]         throw er; // Unhandled 'error' event
[INFO]               ^
[INFO] Error: Failed to call done in a stream handler before 30000ms timeout.
[INFO]     at null._onTimeout (.../node_modules/gulp-jshint/src/stream.js:32:27)
[INFO]     at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by contra** [comment]
You need to return the stream, its in the docs everywhere.
