### ISSUE TITLE
Suspected orchestrator issue

### ISSUE THREAD

**Issue by dokuboyejo** [spalger/gulp-jshint#124]
Hi,

```js
gulp.task('lint', function() {
   return gulp.src('src/ngCacheService.js')
        .pipe(jshint('.jshintrc'))
        .pipe(jshint.reporter('jshint-stylish'))
        .pipe(jshint.reporter('fail'));
});
```

above lint task breaks with following error

```
TypeError: undefined is not a function
    at Gulp.<anonymous> (c:\Workspaces\gulpfile.js:36:50)
    at module.exports (c:\Workspaces\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\Workspaces\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (c:\Workspaces\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (c:\Workspaces\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\ProgramData\nodejs\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)
```

modules

```
"gulp": "^3.8.11"
"gulp-jshint": "~1.11.1"
"jshint-stylish": "^2.0.1"
```

**Comment by spalger** [comment]
Did you figure this out? If you provide the rest of your gulpfile I may be able to help more but closing this as it's definitely not a gulp-jshint issue.

**Comment by dokuboyejo** [comment]
The problem occurs only within jshint, as the rest of my tasks works as normal.

Please see below : my gulpfile

```
taskvar gulp = require('gulp');
var bump = require('gulp-bump');
var gutil = require('gulp-util');
var uglify = require('gulp-uglify');
var sourcemaps = require('gulp-sourcemaps');
var rename = require("gulp-rename");
var fs = require('fs');
var karmaServer = require('karma').Server;
var jshint = require('gulp-jshint').Server;
var karmaConfig = '/test/resources/karma.conf.js';
var cwd = process.cwd();

var getPackageJson = function() {
   return JSON.parse(fs.readFileSync('./package.json', 'utf8'));
};

gulp.task('version-bump', function() {
   return gulp.src([ cwd + '/package.json' ]).pipe(bump()).pipe(gulp.dest('./'));
});

gulp.task('lint', function() {
   return gulp.src('src/ngCacheService.js').pipe(jshint('.jshintrc')).pipe(jshint.reporter('jshint-stylish')).pipe(jshint.reporter('fail'));
})
```

**Comment by dokuboyejo** [comment]
Could you reopen the issue

**Comment by spalger** [comment]
The error above says that it happened on line 36 of your gulpfile, but the one you put here only has ~20 lines
