### ISSUE TITLE
Gulp AssertionError: missing path

### ISSUE THREAD

**Issue by felixbridell** [spalger/gulp-jshint#127]
I can't get JSHint plugin to work in my gulp.js file.
After installing the plugin: npm install gulp-jshint --save-dev and include the: var jshint = require(gulp-jshint); in my gulp.js file I get an error trying to run gulp.

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: missing path
    at Module.require (module.js:364:3)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/felix/GitHub/gulp-test/gulpfile.js:12:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:99:14
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:38:7

Could it be something wrong with my node installation? I hade som problem in the beginning to get it all up because I hade previous installed node through there web package and now I tried to update it from the terminal and install gulp, which did not work. So I removed Node (following this: http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x) and reinstalled it via the Terminal and everything work good until this error. 

I use node v5.0.0
Any ideas?

**Comment by spalger** [comment]
You have to quote the module name you pass to require:
```js
var jshint = require("gulp-jshint");
```
