### ISSUE TITLE
Cannot find module 'jshint/src/cli'

### ISSUE THREAD

**Issue by ganlanyuan** [spalger/gulp-jshint#148]
When I did task
```javascript
gulp.task('jshint', function () {
  gulp.src('src/**/*.js')
      .pipe(jshint())
      .pipe(jshint.reporter('default'))
      .pipe(gulp.dest('src'));
})
```
I got this error
```
Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/web/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
Can you help me fix this?
Thanks

**Comment by ganlanyuan** [comment]
Sorry, I should install `jshint` together with `gulp-jshint`, like the **README** says.
```
npm install jshint gulp-jshint --save-dev
```
Now it's works
