### ISSUE TITLE
 Cannot find module './_customDefaultsAssignIn'

### ISSUE THREAD

**Issue by DameLyngdoh** [spalger/gulp-jshint#154]
Error: Cannot find module './_customDefaultsAssignIn'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\TFS\KM20\NewKMPortal_UI\NewKm_Solution\node_module
s\gulp-jshint\node_modules\lodash\defaults.js:4:30)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

i have the same code running in 3 machines. but in one it is showing this error. tried reinstalling all modules, but nothing happened. 

var gulp = require('gulp'),
	jshint = require('gulp-jshint'),
	stylishJS = require('jshint-stylish');

**Comment by spalger** [comment]
You might need to completely remove your node_modules directory and reinstall that way. This is definitely just an npm install error.
